import subprocess
import time

try:
    result = subprocess.run(["C://Tools//RegRipper3.0-master//RegRipper3.0-master//rip.exe", "-r", "C://Cases//Analysis//Registry//SYSTEM", "-p", "compname"])
    time.sleep(10)
    print("--------------------------------------------------------------------------------------------------------------------------------------------------")
    result = subprocess.run(["C://Tools//RegRipper3.0-master//RegRipper3.0-master//rip.exe", "-r", "C://Cases//Analysis//Registry//SOFTWARE", "-p", "winver"])
    time.sleep(10)
    print("--------------------------------------------------------------------------------------------------------------------------------------------------")
    result = subprocess.run(["C://Tools//RegRipper3.0-master//RegRipper3.0-master//rip.exe", "-r", "C://Cases//Analysis//Registry//SYSTEM", "-p", "timezone"])
    time.sleep(10)
    print("--------------------------------------------------------------------------------------------------------------------------------------------------")
    result = subprocess.run(["C://Tools//RegRipper3.0-master//RegRipper3.0-master//rip.exe", "-r", "C://Cases//Analysis//Registry//SYSTEM", "-p", "nic2"])
    time.sleep(10)
    print("--------------------------------------------------------------------------------------------------------------------------------------------------")
    result = subprocess.run(["C://Tools//RegRipper3.0-master//RegRipper3.0-master//rip.exe", "-r", "C://Cases//Analysis//Registry//SOFTWARE", "-p", "networklist"])
    time.sleep(10)
    print("--------------------------------------------------------------------------------------------------------------------------------------------------")
    result = subprocess.run(["C://Tools//RegRipper3.0-master//RegRipper3.0-master//rip.exe", "-r", "C://Cases//Analysis//Registry//SYSTEM", "-p", "shutdown"])
    time.sleep(10)
    print("--------------------------------------------------------------------------------------------------------------------------------------------------")
    result = subprocess.run(["C://Tools//RegRipper3.0-master//RegRipper3.0-master//rip.exe", "-r", "C://Cases//Analysis//Registry//SOFTWARE", "-p", "defender"])
    time.sleep(10)
    print("--------------------------------------------------------------------------------------------------------------------------------------------------")
    result = subprocess.run(["C://Tools//RegRipper3.0-master//RegRipper3.0-master//rip.exe", "-r", "C://Cases//Analysis//Registry//SAM", "-p", "samparse"])
    time.sleep(10)
    print("--------------------------------------------------------------------------------------------------------------------------------------------------")
    result = subprocess.run(["C://Tools//RegRipper3.0-master//RegRipper3.0-master//rip.exe", "-r", "C://Cases//Analysis//Registry//SOFTWARE", "-p", "profilelist"])
    time.sleep(10)
    print("--------------------------------------------------------------------------------------------------------------------------------------------------")
    result = subprocess.run(["C://Tools//RegRipper3.0-master//RegRipper3.0-master//rip.exe", "-r", "C://Cases//Analysis//Registry//NTUSER.dat", "-p", "userassist"])
    time.sleep(10)
    print("--------------------------------------------------------------------------------------------------------------------------------------------------")
    result = subprocess.run(["C://Tools//RegRipper3.0-master//RegRipper3.0-master//rip.exe", "-r", "C://Cases//Analysis//Registry//NTUSER.dat", "-p", "recentdocs"])
    time.sleep(10)
    print("--------------------------------------------------------------------------------------------------------------------------------------------------")
    result = subprocess.run(["C://Tools//RegRipper3.0-master//RegRipper3.0-master//rip.exe", "-r", "C://Cases//Analysis//Registry//USRCLASS.dat", "-p", "shellbags"])
    time.sleep(10)
    print("--------------------------------------------------------------------------------------------------------------------------------------------------")
    result = subprocess.run(["C://Tools//Get-ZimmermanTools//net6//MFTECmd.exe", "-f", "C://Cases//F//$MFT", "--de", "0"])
    time.sleep(10)
    print("--------------------------------------------------------------------------------------------------------------------------------------------------")
    result = subprocess.run(["C://Tools//Get-ZimmermanTools//net6//MFTECmd.exe", "-f", "C://Cases//F//$MFT", "--csv", "C://Cases/Analysis//NTFS", "--csvf", "MFT.csv"])
    time.sleep(10)
    print("--------------------------------------------------------------------------------------------------------------------------------------------------")
    result = subprocess.run(["C://Tools//Get-ZimmermanTools//net6//MFTECmd.exe", "-f", "C://Cases//F//$Extend//$J", "-m", "C://Cases//F//$MFT", "--csv", "C://Cases/Analysis//NTFS"])
    time.sleep(10)
    print("--------------------------------------------------------------------------------------------------------------------------------------------------")
    result = subprocess.run(["C://Tools//RegRipper3.0-master//RegRipper3.0-master//rip.exe", "-r", "C://Cases//Analysis//Registry//SYSTEM", "-p", "bam"])
    time.sleep(10)
    print("--------------------------------------------------------------------------------------------------------------------------------------------------")
    result = subprocess.run(["C://Tools//RegRipper3.0-master//RegRipper3.0-master//rip.exe", "-r", "C://Cases//Analysis//Registry//SYSTEM", "-p", "appcompatcache"])
    time.sleep(10)
    print("--------------------------------------------------------------------------------------------------------------------------------------------------")
    result = subprocess.run(["C://Tools//Get-ZimmermanTools//net6//AppCompatCacheParser.exe", "-f", "C://Cases//Analysis//Registry//SYSTEM", "--csv", "C://Cases/Analysis//Execution"])
    time.sleep(10)
    print("--------------------------------------------------------------------------------------------------------------------------------------------------")
    result = subprocess.run(["C://Tools//Get-ZimmermanTools//net6//AppCompatCacheParser.exe", "-f", "C://Cases//F//Windows//AppCompat//Programs//Amcache.hve", "--csv", "C://Cases/Analysis//Execution"])
    time.sleep(10)
    print("--------------------------------------------------------------------------------------------------------------------------------------------------")
    result = subprocess.run(["C://Tools//Get-ZimmermanTools//net6//PECmd.exe", "-d", "C://Cases//F//Windows//prefetch", "--csv", "C://Cases/Analysis//Execution"])
    
except subprocess.CalledProcessError as e:
    print(f"Command failed with return code {e.returncode}")
    print(f"Error output: {e.stderr}")